development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: REDISTOGO_URL: redis://redistogo:9b3beda0963b5324f721c84d9acf1ff2@soldierfish.redistogo.com:10389/
  channel_prefix: codenames-backend_production
