development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c54afa0577c5a69aba645bdb5af627a0@soldierfish.redistogo.com:10402/
  channel_prefix: codenames-backend_production
